apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-earphones:4fd0e621e70a5cce460e0954f58dff9a2a3a5d89
        ports:
        - containerPort: 80
