apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-earphones:416fe31e77184a21a45b9bb5cbb36f24d8de10fa
        ports:
        - containerPort: 80
