apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-earphones:3b3683f965cbc0571c11fa60f7dca9f957fb92a0
        ports:
        - containerPort: 80
