apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-backend:8b6f3183e3ee53958d28911df77fce35813bc650
          ports:
            - containerPort: 5000
