apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-electronics:4fd0e621e70a5cce460e0954f58dff9a2a3a5d89
        ports:
        - containerPort: 80
