apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-main:52d4410141c1fd60ff5084b1af97c0b2e928086e
        ports:
        - containerPort: 80

