apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-computers:3b3683f965cbc0571c11fa60f7dca9f957fb92a0
        ports:
        - containerPort: 80
