apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-computers:4fd0e621e70a5cce460e0954f58dff9a2a3a5d89
        ports:
        - containerPort: 80
