apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-computers:416fe31e77184a21a45b9bb5cbb36f24d8de10fa
        ports:
        - containerPort: 80
