apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-phones:4fd0e621e70a5cce460e0954f58dff9a2a3a5d89
        ports:
        - containerPort: 80
