apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 811572529216.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-phones:52d4410141c1fd60ff5084b1af97c0b2e928086e
        ports:
        - containerPort: 80
